# Site settings
name: BSides Bratislava
author: BSidesBA

keywords: bsidesba, bsides bratislava, security bsides, security b-sides, infosec, conference, security, bratislava, informacna bezpecnost
description: >
  BSides Bratislava is a community-driven information security conference. Next iteration will be held on March 15th, 2025 at Faculty of Electrical Engineering and Information Technology of Slovak Technical University.

# Only use this if you are serving your site via Github Pages
github:
  url: "https://bsidesba.sk"

header: yes
header_sm: images/banner-small.png
header_med: images/banner-med.png
header_large: images/banner-large.png
header_xl: images/banner-xl.png


# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]

include: [.well-known]

collections:
  pages:
    output: true
    permalink: /:path

# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

gems:
  - jekyll-feed

feed:
  path: atom.xml
  
# Compress our Css
#sass:
#    style: :compressed

permalink: /blog/:year/:title

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                      #enter your App ID
facebook_locale: en_US
facebook_page:                        #the URL of your Facebook Page
facebook_image:                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user: 
twitter_card: true
twitter_image:                        #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
